#!/usr/bin/env python3
"""Generate the Proof #5 `swarm` proposal (examples/swarm/proposal.json) and
the ownership sidecar (examples/swarm/subsystems.json).

The proposal is the SPEC the multi-agent run implements: 118 tasks across
foundation + 7 subsystems, each with description + acceptance criteria +
files + dependency edges (DAG). Ownership (which of the 4 agent processes
may claim which task) lives in the sidecar so the proposal envelope stays
pure planner protocol (SPEC §9).

Regenerate:
    python examples/swarm/gen_proposal.py
Writes:
    examples/swarm/proposal.json
    examples/swarm/subsystems.json
"""
import json
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

# task(id, subsystem, agent, title, priority, description, acceptance, files, deps)
def t(tid, sub, agent, title, prio, desc, acc, files, deps):
    return {"id": tid, "subsystem": sub, "agent": agent, "title": title,
            "priority": prio, "description": desc, "acceptance": acc,
            "files": files, "deps": deps}

F = "foundation"; CT = "contract"; ST = "storage"; AU = "auth"
GW = "gateway"; WK = "worker"; CL = "cli"; OB = "observe"; IN = "integration"
A, B, C, D = "agent-a", "agent-b", "agent-c", "agent-d"

T = []

# ---------------------------------------------------------------- foundation
T += [
 t("swarm-skeleton", F, A, "swarm repository skeleton", "high",
   "Create examples/swarm/ as a Python project: pyproject.toml declaring package swarm, .gitignore with root-anchored patterns (/events.log, /events.lock, /demo/.frames/, __pycache__/, *.pyc — bare patterns that could match source dirs are forbidden), and swarm/__init__.py placeholder.",
   ["pyproject.toml parses with tomllib and declares project name 'swarm'",
    ".gitignore patterns are root-anchored (leading /) and never bare like 'target'",
    "python -c 'import swarm' succeeds from the repo root"],
   ["pyproject.toml", ".gitignore", "swarm/__init__.py"], []),
 t("swarm-pkg-layout", F, A, "subpackage layout", "high",
   "Create swarm/contract, swarm/storage, swarm/auth, swarm/gateway, swarm/worker, swarm/cli, swarm/observe subpackages, each with an __init__.py (empty docstring for now).",
   ["python -c 'import swarm.contract, swarm.storage, swarm.auth, swarm.gateway, swarm.worker, swarm.cli, swarm.observe' succeeds",
    "each subpackage __init__.py exists"],
   ["swarm/contract/__init__.py", "swarm/storage/__init__.py", "swarm/auth/__init__.py",
    "swarm/gateway/__init__.py", "swarm/worker/__init__.py", "swarm/cli/__init__.py",
    "swarm/observe/__init__.py"], ["swarm-skeleton"]),
 t("version-module", F, A, "swarm version module", "medium",
   "swarm/__init__.py exports __version__ = '0.1.0' and __version_info__ = (0, 1, 0).",
   ["swarm.__version__ == '0.1.0'",
    "swarm.__version_info__ == (0, 1, 0)"],
   ["swarm/__init__.py"], ["swarm-skeleton"]),
 t("shared-errors", F, A, "shared SwarmError base", "high",
   "swarm/errors.py: class SwarmError(Exception) with optional detail dict; str() renders message plus detail. Every module-specific error in the project derives from SwarmError.",
   ["SwarmError('boom', {'k': 1}) str() contains 'boom' and 'k'",
    "tests import SwarmError from swarm.errors"],
   ["swarm/errors.py"], ["swarm-pkg-layout"]),
 t("shared-utils", F, A, "shared utilities", "high",
   "swarm/util.py: utcnow_iso() -> ISO8601 UTC string with Z suffix; slugify(text) -> ascii kebab; ensure_dir(path) mkdir -p.",
   ["utcnow_iso() parses back with datetime.fromisoformat and ends with Z",
    "slugify('Hello, World!') == 'hello-world'",
    "ensure_dir creates nested dirs idempotently"],
   ["swarm/util.py"], ["swarm-pkg-layout"]),
 t("pytest-setup", F, A, "pytest configuration + conftest fixtures", "high",
   "pyproject.toml [tool.pytest.ini_options] with testpaths=['tests'], addopts='-q'; tests/ dir with tests/conftest.py providing fixtures: tmp_swarm (tmp_path-based project dir), db_path (fresh sqlite file path).",
   ["pytest --collect-only exits 0 and finds tests/test_foundation.py",
    "conftest.py defines fixtures tmp_swarm and db_path"],
   ["pyproject.toml", "tests/conftest.py"], ["swarm-pkg-layout"]),
 t("makefile", F, A, "Makefile targets", "low",
   "Makefile with targets: test (pytest), lint (python -m compileall -q swarm tests), clean (rm -rf __pycache__ build dist), help (lists targets).",
   ["make test runs pytest and exits 0",
    "make lint exits 0 on the empty skeleton",
    "make help prints target names"],
   ["Makefile"], ["pytest-setup"]),
 t("ci-script", F, A, "scripts/ci.sh gate", "low",
   "scripts/ci.sh: runs python -m compileall -q swarm tests, then pytest, then a smoke import of every subpackage; set -e; prints 'CI OK'. chmod +x.",
   ["bash scripts/ci.sh exits 0 on the skeleton",
    "script is executable (shebang + chmod)"],
   ["scripts/ci.sh"], ["pytest-setup"]),
 t("foundation-tests", F, A, "foundation unit tests", "medium",
   "tests/test_foundation.py: cover version-module, shared-errors (str rendering, detail), shared-utils (utcnow_iso roundtrip, slugify cases, ensure_dir).",
   ["pytest tests/test_foundation.py passes",
    "each util/error/version behavior has >= 1 assertion"],
   ["tests/test_foundation.py"], ["version-module", "shared-errors", "shared-utils"]),
]

# ----------------------------------------------------------------- contract
T += [
 t("contract-schema", CT, A, "wire message schema dataclasses", "high",
   "swarm/contract/schema.py: frozen dataclasses UserMsg(id: str, name: str, role: str), JobMsg(id: str, user_id: str, kind: str, payload: dict, status: str), EventMsg(id: str, type: str, data: dict, ts: str). as_dict() returns dict with canonical key order; repr is deterministic.",
   ["UserMsg('u1','Ada','admin').as_dict() == {'id':'u1','name':'Ada','role':'admin'}",
    "dataclasses are frozen (no mutation)",
    "JobMsg accepts arbitrary payload dict"],
   ["swarm/contract/schema.py"], ["shared-errors"]),
 t("contract-errors", CT, A, "ContractError with field context", "high",
   "swarm/contract/errors.py: ContractError(SwarmError) with msg, field, value attributes; str() renders 'field <field>: <msg>'.",
   ["ContractError('required', 'name', None).str() contains 'name' and 'required'",
    "ContractError is a SwarmError subclass"],
   ["swarm/contract/errors.py"], ["shared-errors"]),
 t("contract-codec", CT, A, "canonical JSON codec", "high",
   "swarm/contract/codec.py: to_json(msg) -> str (canonical key order, ensure_ascii=False, sort_keys=True) and from_json(text, cls) -> dataclass instance; unknown top-level keys ignored by default.",
   ["to_json/from_json roundtrip preserves all fields",
    "output key order is sorted (canonical)",
    "from_json ignores unknown top-level keys"],
   ["swarm/contract/codec.py"], ["contract-schema", "contract-errors"]),
 t("contract-validate", CT, A, "message validation rules", "high",
   "swarm/contract/validate.py: validate(msg) checks required fields non-empty, role in {admin, operator, read}, status in {todo, running, done, failed}, ts parses as ISO8601; raises ContractError with field context on first violation.",
   ["missing id raises ContractError field='id'",
    "bad role raises ContractError field='role'",
    "valid message passes without error"],
   ["swarm/contract/validate.py"], ["contract-schema", "contract-errors"]),
 t("contract-versioning", CT, A, "wire version header + check", "medium",
   "swarm/contract/version.py: WIRE_VERSION = 1; encode(text, version) prefixes 'v1:' ; check_version(header) returns int or raises ContractError for unsupported versions.",
   ["encode/decode roundtrip at version 1",
    "check_version('v1') == 1",
    "check_version('v0') raises ContractError"],
   ["swarm/contract/version.py"], ["contract-errors"]),
 t("contract-iso-time", CT, A, "ISO8601 UTC time helpers", "medium",
   "swarm/contract/timeutil.py: parse_iso(s) -> datetime (requires UTC or Z), format_iso(dt) -> 'YYYY-MM-DDTHH:MM:SS.mmmZ' (UTC).",
   ["parse_iso(format_iso(utcnow)) roundtrips to same instant",
    "parse_iso rejects naive local time (no tzinfo)"],
   ["swarm/contract/timeutil.py"], ["contract-schema"]),
 t("contract-size-limit", CT, A, "message size limit guard", "medium",
   "swarm/contract/limits.py: MAX_MESSAGE_BYTES = 65536; enforce_size(text) raises ContractError when len(text.encode()) exceeds the limit.",
   ["65536-byte payload raises ContractError",
    "small payload passes"],
   ["swarm/contract/limits.py"], ["contract-codec"]),
 t("contract-unknown-fields", CT, A, "unknown-field policy (ignore / strict)", "medium",
   "swarm/contract/codec.py: add strict mode — from_json(text, cls, strict=True) raises ContractError on unknown top-level keys; default stays lenient.",
   ["strict=True rejects unknown key",
    "default ignores unknown key"],
   ["swarm/contract/codec.py"], ["contract-codec"]),
 t("contract-nested", CT, A, "nested payload validation", "medium",
   "swarm/contract/validate.py: validate_job_payload(payload, kind) — kind 'echo' requires payload {'text': str}; kind 'add' requires {'a': number, 'b': number}; unknown kind raises ContractError field='kind'.",
   ["echo with text passes; without raises ContractError",
    "add with numbers passes; with strings raises",
    "unknown kind raises ContractError field='kind'"],
   ["swarm/contract/validate.py"], ["contract-validate"]),
 t("contract-tests-schema", CT, A, "schema tests", "medium",
   "tests/test_contract_schema.py covering as_dict order, frozen dataclasses, JobMsg payload dict.",
   ["pytest tests/test_contract_schema.py passes"], ["tests/test_contract_schema.py"], ["contract-schema"]),
 t("contract-tests-codec", CT, A, "codec tests", "medium",
   "tests/test_contract_codec.py: roundtrips for all three messages, canonical ordering, unknown-key ignore.",
   ["pytest tests/test_contract_codec.py passes"], ["tests/test_contract_codec.py"], ["contract-codec"]),
 t("contract-tests-validate", CT, A, "validation tests", "medium",
   "tests/test_contract_validate.py: each rule failure asserts field context; valid messages pass.",
   ["pytest tests/test_contract_validate.py passes"], ["tests/test_contract_validate.py"], ["contract-validate"]),
 t("contract-tests-version", CT, A, "versioning tests", "low",
   "tests/test_contract_version.py: roundtrip, v1 ok, v0/v2 rejected.",
   ["pytest tests/test_contract_version.py passes"], ["tests/test_contract_version.py"], ["contract-versioning"]),
 t("contract-tests-iso", CT, A, "time helper tests", "low",
   "tests/test_contract_timeutil.py: roundtrip, tz rejection.",
   ["pytest tests/test_contract_timeutil.py passes"], ["tests/test_contract_timeutil.py"], ["contract-iso-time"]),
 t("contract-tests-limit", CT, A, "size limit tests", "low",
   "tests/test_contract_limits.py: boundary at 65536 bytes.",
   ["pytest tests/test_contract_limits.py passes"], ["tests/test_contract_limits.py"], ["contract-size-limit"]),
 t("contract-tests-unknown", CT, A, "strict-mode tests", "low",
   "tests/test_contract_unknown.py: lenient default vs strict rejection.",
   ["pytest tests/test_contract_unknown.py passes"], ["tests/test_contract_unknown.py"], ["contract-unknown-fields"]),
 t("contract-docs", CT, A, "contract README", "low",
   "swarm/contract/README.md: message catalog (UserMsg/JobMsg/EventMsg), wire version, strict/lenient policy, size limit.",
   ["swarm/contract/README.md exists and documents the message catalog"],
   ["swarm/contract/README.md"], ["contract-tests-codec"]),
]

# ------------------------------------------------------------------ storage
T += [
 t("storage-ddl", ST, B, "SQLite schema DDL", "high",
   "swarm/storage/ddl.py: SCHEMA_SQL string with CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL), jobs(id TEXT PRIMARY KEY, user_id TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL), events(id TEXT PRIMARY KEY, type TEXT NOT NULL, data TEXT NOT NULL, ts TEXT NOT NULL); plus indexes on jobs(status), events(ts).",
   ["executing SCHEMA_SQL twice on the same connection is idempotent",
    "PRAGMA table_info reports the 8 jobs columns"],
   ["swarm/storage/ddl.py"], ["swarm-pkg-layout"]),
 t("storage-errors", ST, B, "storage error hierarchy", "high",
   "swarm/storage/errors.py: StorageError(SwarmError), NotFound(StorageError, carries id), ConstraintViolation(StorageError).",
   ["NotFound('user','u1') str() contains 'user' and 'u1'",
    "both subclasses derive from StorageError"],
   ["swarm/storage/errors.py"], ["shared-errors"]),
 t("storage-conn", ST, B, "connection context manager (WAL)", "high",
   "swarm/storage/conn.py: connect(path) -> sqlite3.Connection with PRAGMA journal_mode=WAL, foreign_keys=ON; Database context manager class managing open/close and a thread-local connection.",
   ["journal_mode == 'wal' after connect",
    "context manager closes the connection on exit"],
   ["swarm/storage/conn.py"], ["storage-ddl"]),
 t("storage-init", ST, B, "idempotent database init", "high",
   "swarm/storage/init.py: init_db(conn) applies SCHEMA_SQL and sets PRAGMA user_version = 1; safe to call repeatedly.",
   ["init_db twice raises no error",
    "PRAGMA user_version == 1 after init"],
   ["swarm/storage/init.py"], ["storage-ddl", "storage-conn"]),
 t("storage-repo-users", ST, B, "users repository", "high",
   "swarm/storage/users.py: UserRepo(conn) with create(user_id, name, role), get(user_id) (raises NotFound), list(limit=100), delete(user_id) (raises NotFound if absent).",
   ["create then get returns the row with matching fields",
    "get on missing id raises NotFound",
    "list returns rows newest-first"],
   ["swarm/storage/users.py"], ["storage-init", "storage-errors"]),
 t("storage-repo-jobs", ST, B, "jobs repository with atomic claim", "high",
   "swarm/storage/jobs.py: JobRepo(conn) with create(job_id, user_id, kind, payload), get(job_id), claim() — atomically sets one todo job to running (UPDATE ... WHERE status='todo' RETURNING, or immediate transaction) and returns it or None; complete(job_id) sets status=done, updated_at; fail(job_id, reason) sets status=failed, attempts=attempts+1.",
   ["claim() returns exactly one todo job and flips it to running",
    "two sequential claim() calls return different jobs (no double-claim)",
    "fail() increments attempts"],
   ["swarm/storage/jobs.py"], ["storage-init", "storage-errors"]),
 t("storage-repo-events", ST, B, "events repository", "medium",
   "swarm/storage/events.py: EventRepo(conn) with append(event_id, type, data, ts), recent(limit=50) newest-first, list_by_type(type, limit=50).",
   ["append then recent returns the event first",
    "recent respects limit and ordering",
    "list_by_type filters correctly"],
   ["swarm/storage/events.py"], ["storage-init", "storage-errors"]),
 t("storage-migrations", ST, B, "versioned migration runner", "medium",
   "swarm/storage/migrations.py: MIGRATIONS = [(1, SCHEMA_SQL)]; migrate(conn) applies pending migrations in order and bumps user_version; upgrade path from version 0.",
   ["migrate on a fresh db ends at latest version",
    "migrate on an already-current db is a no-op"],
   ["swarm/storage/migrations.py"], ["storage-ddl", "storage-init"]),
 t("storage-transactions", ST, B, "transaction context manager", "medium",
   "swarm/storage/txn.py: transaction(conn) context manager committing on success, rolling back on exception.",
   ["committed writes persist after context exit",
    "exception inside the block rolls back all writes"],
   ["swarm/storage/txn.py"], ["storage-conn"]),
 t("storage-tests-ddl", ST, B, "DDL tests", "medium",
   "tests/test_storage_ddl.py: idempotency + column inventory.",
   ["pytest tests/test_storage_ddl.py passes"], ["tests/test_storage_ddl.py"], ["storage-ddl"]),
 t("storage-tests-conn", ST, B, "connection tests", "medium",
   "tests/test_storage_conn.py: WAL mode, context close, foreign_keys on.",
   ["pytest tests/test_storage_conn.py passes"], ["tests/test_storage_conn.py"], ["storage-conn"]),
 t("storage-tests-users", ST, B, "users repo tests", "medium",
   "tests/test_storage_users.py: CRUD + NotFound paths.",
   ["pytest tests/test_storage_users.py passes"], ["tests/test_storage_users.py"], ["storage-repo-users"]),
 t("storage-tests-jobs", ST, B, "jobs repo tests (atomicity)", "high",
   "tests/test_storage_jobs.py: claim atomicity — open two connections, claim from both, assert disjoint results and no double-claim; complete/fail transitions; attempts increment.",
   ["pytest tests/test_storage_jobs.py passes",
    "the two-connection claim test is included"],
   ["tests/test_storage_jobs.py"], ["storage-repo-jobs"]),
 t("storage-tests-events", ST, B, "events repo tests", "low",
   "tests/test_storage_events.py: append/recent/list_by_type.",
   ["pytest tests/test_storage_events.py passes"], ["tests/test_storage_events.py"], ["storage-repo-events"]),
 t("storage-tests-migrations", ST, B, "migration tests", "low",
   "tests/test_storage_migrations.py: fresh + already-current cases.",
   ["pytest tests/test_storage_migrations.py passes"], ["tests/test_storage_migrations.py"], ["storage-migrations"]),
 t("storage-tests-txn", ST, B, "transaction tests", "low",
   "tests/test_storage_txn.py: commit vs rollback.",
   ["pytest tests/test_storage_txn.py passes"], ["tests/test_storage_txn.py"], ["storage-transactions"]),
 t("storage-bench", ST, B, "insert throughput sanity bench", "low",
   "scripts/bench_storage.py: inserts 1000 jobs via JobRepo and asserts wall time < 5s, printing rows/sec.",
   ["python scripts/bench_storage.py exits 0 and prints rows/sec"],
   ["scripts/bench_storage.py"], ["storage-repo-jobs"]),
 t("storage-docs", ST, B, "storage README", "low",
   "swarm/storage/README.md: schema overview, repo API, claim semantics, migration policy.",
   ["swarm/storage/README.md exists and documents claim semantics"],
   ["swarm/storage/README.md"], ["storage-tests-jobs"]),
]

# --------------------------------------------------------------------- auth
T += [
 t("auth-claims", AU, B, "token claims model", "high",
   "swarm/auth/claims.py: make_claims(user_id, scopes, ttl_seconds=3600) -> dict {sub, scopes: [str], exp: unix}; parse_claims(d) validates presence/types and raises AuthError on missing exp.",
   ["make_claims roundtrips through parse_claims",
    "exp is a future unix timestamp within ttl"],
   ["swarm/auth/claims.py"], ["shared-errors"]),
 t("auth-errors", AU, B, "auth error hierarchy", "high",
   "swarm/auth/errors.py: AuthError(SwarmError), InvalidToken(AuthError), TokenExpired(AuthError), InsufficientScope(AuthError, carries required scope).",
   ["all four classes derive from SwarmError via AuthError",
    "InsufficientScope str() mentions the required scope"],
   ["swarm/auth/errors.py"], ["shared-errors"]),
 t("auth-hmac", AU, B, "HMAC token sign/verify (stdlib)", "high",
   "swarm/auth/token.py: issue(secret, claims) -> token string '<b64payload>.<b64sig>' where sig = HMAC-SHA256(secret, payload); verify(secret, token) -> claims dict or raises InvalidToken/TokenExpired. No third-party deps (hmac, hashlib, base64, json).",
   ["issue then verify returns the claims",
    "tampered payload raises InvalidToken",
    "wrong secret raises InvalidToken"],
   ["swarm/auth/token.py"], ["auth-claims", "auth-errors"]),
 t("auth-constant-time", AU, B, "constant-time signature compare", "medium",
   "swarm/auth/token.py: signature comparison must use hmac.compare_digest (never ==).",
   ["verify rejects a near-miss signature",
    "source uses hmac.compare_digest for the signature check"],
   ["swarm/auth/token.py"], ["auth-hmac"]),
 t("auth-scopes", AU, B, "scope checks", "medium",
   "swarm/auth/scopes.py: requires(claims, scope) raises InsufficientScope unless scope in claims['scopes']; SCOPES = ['admin', 'operator', 'read'].",
   ["requires passes when scope present",
    "requires raises InsufficientScope when absent"],
   ["swarm/auth/scopes.py"], ["auth-claims", "auth-errors"]),
 t("auth-rotate", AU, B, "key rotation support", "medium",
   "swarm/auth/keys.py: KeyRing with current secret + list of retired secrets; verify accepts any active secret; issue uses current; retire(key) removes it.",
   ["token issued under old key verifies while old key active",
    "after retire(old), that token raises InvalidToken"],
   ["swarm/auth/keys.py"], ["auth-hmac"]),
 t("auth-tests-claims", AU, B, "claims tests", "low",
   "tests/test_auth_claims.py: roundtrip, exp validity.",
   ["pytest tests/test_auth_claims.py passes"], ["tests/test_auth_claims.py"], ["auth-claims"]),
 t("auth-tests-hmac", AU, B, "HMAC tests", "high",
   "tests/test_auth_token.py: issue/verify, tamper, wrong secret, expiry (exp in past -> TokenExpired).",
   ["pytest tests/test_auth_token.py passes"], ["tests/test_auth_token.py"], ["auth-hmac"]),
 t("auth-tests-scopes", AU, B, "scope tests", "low",
   "tests/test_auth_scopes.py: pass/fail matrix.",
   ["pytest tests/test_auth_scopes.py passes"], ["tests/test_auth_scopes.py"], ["auth-scopes"]),
 t("auth-tests-rotate", AU, B, "rotation tests", "low",
   "tests/test_auth_keys.py: retire semantics.",
   ["pytest tests/test_auth_keys.py passes"], ["tests/test_auth_keys.py"], ["auth-rotate"]),
 t("auth-tests-errors", AU, B, "error tests", "low",
   "tests/test_auth_errors.py: hierarchy + str rendering.",
   ["pytest tests/test_auth_errors.py passes"], ["tests/test_auth_errors.py"], ["auth-errors"]),
 t("auth-docs", AU, B, "auth README", "low",
   "swarm/auth/README.md: claims, token format, scope model, rotation policy.",
   ["swarm/auth/README.md exists and documents token format"],
   ["swarm/auth/README.md"], ["auth-tests-hmac"]),
]

# ------------------------------------------------------------------ gateway
T += [
 t("gw-app", GW, A, "WSGI application factory", "high",
   "swarm/gateway/app.py: create_app(storage_path) -> callable WSGI app wiring routers, auth guard, error handler, /healthz. Uses wsgiref-compatible plain WSGI (stdlib only).",
   ["create_app returns a callable(environ, start_response)",
    "GET /healthz on the app returns 200 and JSON {\"ok\": true}"],
   ["swarm/gateway/app.py"], ["storage-init", "auth-hmac", "contract-codec"]),
 t("gw-serialization", GW, A, "request/response codec wiring", "medium",
   "swarm/gateway/serialize.py: json_body(environ) -> dict (decodes + validates via contract codec), respond(start_response, status, payload) -> bytes with application/json content-type.",
   ["json_body parses a JSON request body",
    "respond emits correct status line and JSON bytes"],
   ["swarm/gateway/serialize.py"], ["contract-codec", "contract-errors"]),
 t("gw-routes-users", GW, A, "users router", "high",
   "swarm/gateway/routes_users.py: handle(environ, start_response, repo) — POST /users {id,name,role} creates + returns 201; GET /users returns list.",
   ["POST /users returns 201 and the created user",
    "GET /users returns the stored users"],
   ["swarm/gateway/routes_users.py"], ["gw-app", "storage-repo-users", "gw-serialization"]),
 t("gw-routes-jobs", GW, A, "jobs router", "high",
   "swarm/gateway/routes_jobs.py: POST /jobs {user_id, kind, payload} creates job + 201; GET /jobs/<id> returns job or 404.",
   ["POST /jobs returns 201 with the job id",
    "GET /jobs/<id> returns the job; unknown id -> 404"],
   ["swarm/gateway/routes_jobs.py"], ["gw-app", "storage-repo-jobs", "gw-serialization"]),
 t("gw-routes-events", GW, A, "events router", "medium",
   "swarm/gateway/routes_events.py: GET /events?limit=N returns recent events.",
   ["GET /events returns events newest-first",
    "limit parameter is honored"],
   ["swarm/gateway/routes_events.py"], ["gw-app", "storage-repo-events", "gw-serialization"]),
 t("gw-auth-guard", GW, A, "Bearer token auth guard", "high",
   "swarm/gateway/guard.py: wrap(app, keyring) middleware — requests with Authorization: Bearer <token> are verified; /healthz is public; missing/invalid token -> 401 JSON; claims exposed via environ['swarm.identity'].",
   ["no token -> 401 JSON",
    "valid token passes and sets environ['swarm.identity']",
    "/healthz bypasses auth"],
   ["swarm/gateway/guard.py"], ["gw-app", "auth-hmac", "auth-constant-time"]),
 t("gw-validation", GW, A, "request validation wiring", "medium",
   "swarm/gateway/validate.py: validate_request(method, path, body) using contract validation; bad requests -> 400 with field context.",
   ["invalid body returns 400 with field in the error",
    "valid body passes"],
   ["swarm/gateway/validate.py"], ["contract-validate", "gw-serialization"]),
 t("gw-errors", GW, A, "JSON error responses", "medium",
   "swarm/gateway/errors.py: error_response(start_response, status, code, message) -> bytes {'error': code, 'message': message}; maps SwarmError subclasses to status codes.",
   ["error_response produces the right status + JSON shape",
    "NotFound maps to 404, ContractError to 400, AuthError to 401"],
   ["swarm/gateway/errors.py"], ["gw-app", "shared-errors"]),
 t("gw-rate-limit", GW, A, "in-memory per-IP rate limit", "medium",
   "swarm/gateway/ratelimit.py: TokenBucket per client IP (10 req / 10s) in a dict with periodic cleanup; exceeded -> 429 JSON.",
   ["11th request within the window -> 429",
    "window expiry resets the bucket"],
   ["swarm/gateway/ratelimit.py"], ["gw-app"]),
 t("gw-logging", GW, A, "request logging via observe", "medium",
   "swarm/gateway/log.py: middleware logging method, path, status, duration_ms through swarm.observe.logging.get_logger('gateway').",
   ["a request through the logging middleware emits one structured log line"],
   ["swarm/gateway/log.py"], ["obs-logging"]),
 t("gw-tests-app", GW, A, "app factory tests", "medium",
   "tests/test_gateway_app.py: /healthz 200 + JSON; app is callable.",
   ["pytest tests/test_gateway_app.py passes"], ["tests/test_gateway_app.py"], ["gw-app"]),
 t("gw-tests-routes", GW, A, "routes tests (WSGI client)", "high",
   "tests/test_gateway_routes.py: users + jobs + events routes via a minimal WSGI test client against a tmp db.",
   ["pytest tests/test_gateway_routes.py passes"], ["tests/test_gateway_routes.py"], ["gw-routes-users", "gw-routes-jobs", "gw-routes-events"]),
 t("gw-tests-auth", GW, A, "auth guard tests", "high",
   "tests/test_gateway_guard.py: 401 without token, pass with token, /healthz public.",
   ["pytest tests/test_gateway_guard.py passes"], ["tests/test_gateway_guard.py"], ["gw-auth-guard"]),
 t("gw-tests-validation", GW, A, "validation tests", "low",
   "tests/test_gateway_validate.py: 400 on invalid body with field context.",
   ["pytest tests/test_gateway_validate.py passes"], ["tests/test_gateway_validate.py"], ["gw-validation"]),
 t("gw-tests-ratelimit", GW, A, "rate limit tests", "low",
   "tests/test_gateway_ratelimit.py: 429 path + reset.",
   ["pytest tests/test_gateway_ratelimit.py passes"], ["tests/test_gateway_ratelimit.py"], ["gw-rate-limit"]),
 t("gw-docs", GW, A, "gateway README", "low",
   "swarm/gateway/README.md: route table, auth, rate limits, error shape.",
   ["swarm/gateway/README.md exists with the route table"],
   ["swarm/gateway/README.md"], ["gw-tests-auth"]),
]

# ------------------------------------------------------------------- worker
T += [
 t("worker-job-fn", WK, C, "job dispatch table", "high",
   "swarm/worker/jobs.py: JOB_KINDS = {'echo': fn_echo, 'add': fn_add}; fn_echo(payload) returns {'echo': payload['text']}; fn_add(payload) returns {'sum': a+b}; unknown kind raises ValueError.",
   ["fn_echo returns {'echo': ...}",
    "fn_add returns {'sum': ...}",
    "unknown kind raises ValueError"],
   ["swarm/worker/jobs.py"], ["contract-schema"]),
 t("worker-errors", WK, C, "worker errors", "low",
   "swarm/worker/errors.py: WorkerError(SwarmError), JobExecutionError(WorkerError, carries job_id and kind).",
   ["JobExecutionError('j1','echo') str() contains 'j1' and 'echo'"],
   ["swarm/worker/errors.py"], ["shared-errors"]),
 t("worker-poll", WK, C, "job polling via atomic claim", "high",
   "swarm/worker/poll.py: next_ready_job(conn) -> row | None using JobRepo.claim() (atomic todo->running).",
   ["next_ready_job returns a running-status job row",
    "returns None when the queue is empty"],
   ["swarm/worker/poll.py"], ["storage-repo-jobs"]),
 t("worker-exec", WK, C, "single-job executor", "high",
   "swarm/worker/executor.py: run_once(conn, job_fn=JOB_KINDS) — poll, execute, complete(job_id) on success; on failure fail(job_id, reason) with attempt counter; writes an event row via EventRepo on completion.",
   ["successful run marks the job done and appends an event",
    "failing kind marks the job failed and increments attempts",
    "empty queue is a silent no-op"],
   ["swarm/worker/executor.py"], ["worker-poll", "worker-job-fn", "storage-repo-events"]),
 t("worker-retry", WK, C, "retry with backoff", "medium",
   "swarm/worker/retry.py: RETRY_LIMIT = 3; requeue_failed(conn, delay_fn) — failed jobs with attempts < RETRY_LIMIT are set back to todo; attempts >= limit stay failed.",
   ["failed job with attempts=1 is requeued to todo",
    "failed job with attempts=3 stays failed"],
   ["swarm/worker/retry.py"], ["storage-repo-jobs"]),
 t("worker-queue", WK, C, "bounded in-process queue", "medium",
   "swarm/worker/queue.py: class JobQueue with put(job_id) (blocking when full, maxsize=100), get(timeout) -> job_id | None.",
   ["put/get roundtrip in FIFO order",
    "get with timeout returns None when empty"],
   ["swarm/worker/queue.py"], ["shared-errors"]),
 t("worker-pool", WK, C, "N-thread worker pool", "high",
   "swarm/worker/pool.py: WorkerPool(n=2, conn_factory) — n threads each looping run_once; start()/stop() lifecycle; stop drains the current job before joining.",
   ["pool processes >= 1 queued job to completion",
    "stop() returns and all threads exit"],
   ["swarm/worker/pool.py"], ["worker-queue", "worker-exec"]),
 t("worker-graceful", WK, C, "graceful shutdown drain", "medium",
   "swarm/worker/pool.py: stop(wait=True) drains in-flight jobs; wait=False interrupts. Documented drain semantics in docstring.",
   ["stop(wait=True) blocks until in-flight job finishes",
    "stop(wait=False) returns promptly"],
   ["swarm/worker/pool.py"], ["worker-pool"]),
 t("worker-tests-job-fn", WK, C, "job fn tests", "low",
   "tests/test_worker_jobs.py: echo/add/unknown-kind.",
   ["pytest tests/test_worker_jobs.py passes"], ["tests/test_worker_jobs.py"], ["worker-job-fn"]),
 t("worker-tests-poll", WK, C, "poll tests", "medium",
   "tests/test_worker_poll.py: claim semantics — two polls never return the same todo job.",
   ["pytest tests/test_worker_poll.py passes"], ["tests/test_worker_poll.py"], ["worker-poll"]),
 t("worker-tests-exec", WK, C, "executor tests", "high",
   "tests/test_worker_executor.py: success path (done + event), failure path (failed + attempts), empty queue no-op.",
   ["pytest tests/test_worker_executor.py passes"], ["tests/test_worker_executor.py"], ["worker-exec"]),
 t("worker-tests-retry", WK, C, "retry tests", "low",
   "tests/test_worker_retry.py: requeue threshold.",
   ["pytest tests/test_worker_retry.py passes"], ["tests/test_worker_retry.py"], ["worker-retry"]),
 t("worker-tests-pool", WK, C, "pool tests", "medium",
   "tests/test_worker_pool.py: pool completes queued jobs; stop exits.",
   ["pytest tests/test_worker_pool.py passes"], ["tests/test_worker_pool.py"], ["worker-pool"]),
 t("worker-docs", WK, C, "worker README", "low",
   "swarm/worker/README.md: dispatch kinds, poll/execute loop, retry policy, pool lifecycle.",
   ["swarm/worker/README.md exists and documents the retry policy"],
   ["swarm/worker/README.md"], ["worker-tests-exec"]),
]

# ---------------------------------------------------------------------- cli
T += [
 t("cli-parser", CL, C, "admin CLI parser", "high",
   "swarm/cli/parser.py: argparse with global --db PATH (default ./swarm.db) and subcommands users, jobs, events, status, retry.",
   ["python -m swarm.cli --help exits 0 and lists all 5 subcommands",
    "unknown subcommand exits with code 2"],
   ["swarm/cli/parser.py"], ["storage-init"]),
 t("cli-users", CL, C, "users subcommand", "medium",
   "swarm/cli/parser.py: users list prints id/name/role table; users create <id> <name> <role> inserts.",
   ["users create then users list shows the new user"],
   ["swarm/cli/parser.py"], ["cli-parser", "storage-repo-users"]),
 t("cli-jobs", CL, C, "jobs subcommand", "medium",
   "swarm/cli/parser.py: jobs list [--status S] prints jobs; jobs retry <id> resets a failed job to todo.",
   ["jobs list prints created jobs",
    "jobs retry flips a failed job to todo"],
   ["swarm/cli/parser.py"], ["cli-parser", "storage-repo-jobs", "worker-retry"]),
 t("cli-events", CL, C, "events subcommand", "low",
   "swarm/cli/parser.py: events [-n N] tails recent events.",
   ["events -n 2 prints at most 2 events"],
   ["swarm/cli/parser.py"], ["cli-parser", "storage-repo-events"]),
 t("cli-output", CL, C, "table/JSON output formatting", "low",
   "swarm/cli/output.py: render_table(headers, rows) and render_json(obj); --json flag switches output.",
   ["render_table aligns columns",
    "--json emits valid JSON"],
   ["swarm/cli/output.py"], ["cli-parser"]),
 t("cli-errors", CL, C, "friendly CLI errors + exit codes", "low",
   "swarm/cli/parser.py: usage errors exit 1 with message to stderr; runtime errors (NotFound etc.) exit 2 with 'error: <msg>'.",
   ["missing required arg exits 1",
    "jobs retry on unknown id exits 2 with error message"],
   ["swarm/cli/parser.py"], ["cli-parser"]),
 t("cli-tests-parser", CL, C, "parser tests", "low",
   "tests/test_cli_parser.py: subcommand dispatch + exit codes.",
   ["pytest tests/test_cli_parser.py passes"], ["tests/test_cli_parser.py"], ["cli-parser"]),
 t("cli-tests-users", CL, C, "users CLI tests", "low",
   "tests/test_cli_users.py: create/list via subprocess or main() against tmp db.",
   ["pytest tests/test_cli_users.py passes"], ["tests/test_cli_users.py"], ["cli-users"]),
 t("cli-tests-jobs", CL, C, "jobs CLI tests", "low",
   "tests/test_cli_jobs.py: list + retry.",
   ["pytest tests/test_cli_jobs.py passes"], ["tests/test_cli_jobs.py"], ["cli-jobs"]),
 t("cli-tests-events", CL, C, "events CLI tests", "low",
   "tests/test_cli_events.py: tail limit.",
   ["pytest tests/test_cli_events.py passes"], ["tests/test_cli_events.py"], ["cli-events"]),
 t("cli-docs", CL, C, "CLI README", "low",
   "swarm/cli/README.md: command reference + exit codes.",
   ["swarm/cli/README.md exists with the command reference"],
   ["swarm/cli/README.md"], ["cli-tests-jobs"]),
]

# ------------------------------------------------------------------ observe
T += [
 t("obs-logging", OB, D, "structured JSON logging", "high",
   "swarm/observe/logging.py: get_logger(name) -> stdlib logging.Logger with a JSON formatter emitting one JSON object per line {ts, level, logger, msg, **extra}; configure(level).",
   ["a log line parses as JSON with ts/level/logger keys",
    "extra kwargs appear as top-level JSON fields"],
   ["swarm/observe/logging.py"], ["shared-utils"]),
 t("obs-metrics", OB, D, "metrics registry", "high",
   "swarm/observe/metrics.py: Registry with counter(name, labels=None) increment and gauge(name, value, labels); snapshot() -> list of (name, labels, value).",
   ["counter increments accumulate",
    "snapshot reflects counters and gauges"],
   ["swarm/observe/metrics.py"], ["shared-errors"]),
 t("obs-endpoint", OB, D, "metrics text renderer", "medium",
   "swarm/observe/render.py: render_metrics(registry) -> str in Prometheus text format (name{labels} value).",
   ["render output lines are 'name{label=\"v\"} value' shaped",
    "renders counters and gauges"],
   ["swarm/observe/render.py"], ["obs-metrics"]),
 t("obs-context", OB, D, "request-id propagation", "medium",
   "swarm/observe/context.py: contextvars-based request_id; set_request_id(), get_request_id(); logging middleware injects it into structured lines.",
   ["set/get roundtrip within one context",
    "log lines carry the active request_id"],
   ["swarm/observe/context.py"], ["obs-logging"]),
 t("obs-threshold", OB, D, "alert threshold counters", "low",
   "swarm/observe/threshold.py: ThresholdCounter(registry, name, limit) — inc() returns True when crossing the limit (once), exposing a boolean alert flag in the registry.",
   ["crossing the limit returns True exactly once",
    "alert flag appears in snapshot"],
   ["swarm/observe/threshold.py"], ["obs-metrics"]),
 t("obs-tests-logging", OB, D, "logging tests", "medium",
   "tests/test_observe_logging.py: JSON shape + extra fields.",
   ["pytest tests/test_observe_logging.py passes"], ["tests/test_observe_logging.py"], ["obs-logging"]),
 t("obs-tests-metrics", OB, D, "metrics tests", "medium",
   "tests/test_observe_metrics.py: counters, gauges, snapshot.",
   ["pytest tests/test_observe_metrics.py passes"], ["tests/test_observe_metrics.py"], ["obs-metrics"]),
 t("obs-tests-render", OB, D, "renderer tests", "low",
   "tests/test_observe_render.py: text format lines.",
   ["pytest tests/test_observe_render.py passes"], ["tests/test_observe_render.py"], ["obs-endpoint"]),
 t("obs-tests-context", OB, D, "context tests", "low",
   "tests/test_observe_context.py: propagation + isolation across contexts.",
   ["pytest tests/test_observe_context.py passes"], ["tests/test_observe_context.py"], ["obs-context"]),
 t("obs-docs", OB, D, "observe README", "low",
   "swarm/observe/README.md: logging format, metric types, request-id flow.",
   ["swarm/observe/README.md exists and documents the log line format"],
   ["swarm/observe/README.md"], ["obs-tests-logging"]),
]

# -------------------------------------------------------------- integration
T += [
 t("int-storage-contract", IN, D, "storage rows <-> contract messages", "high",
   "swarm/integration/mapping.py: job_row_to_msg(row) -> JobMsg and msg_to_job_row(msg); integration tests assert the mapping survives a storage roundtrip.",
   ["a JobMsg stored as a row and read back maps to an equal JobMsg",
    "mapping tests pass under pytest"],
   ["swarm/integration/mapping.py", "tests/test_integration_mapping.py"],
   ["storage-repo-jobs", "contract-codec", "contract-validate"]),
 t("int-gateway-worker", IN, D, "gateway submit -> worker processes", "high",
   "tests/test_integration_gateway_worker.py: create user, POST /jobs via WSGI client, run worker run_once, assert job done and an event recorded.",
   ["pytest tests/test_integration_gateway_worker.py passes"],
   ["tests/test_integration_gateway_worker.py"], ["gw-routes-jobs", "worker-exec"]),
 t("int-e2e", IN, D, "full lifecycle end-to-end", "high",
   "tests/test_integration_e2e.py: create user -> auth token -> submit echo job via gateway -> worker completes -> GET /jobs/<id> shows done -> GET /events shows the event -> CLI status shows counts.",
   ["pytest tests/test_integration_e2e.py passes"],
   ["tests/test_integration_e2e.py"], ["int-gateway-worker", "gw-auth-guard", "cli-jobs", "obs-metrics"]),
 t("int-demo-script", IN, D, "demo driver script", "medium",
   "demo/run_demo.py: drives the e2e scenario with visible console output (timestamps, per-step prints) against a fresh tmp db, exits 0.",
   ["python demo/run_demo.py exits 0 and prints the full lifecycle"],
   ["demo/run_demo.py"], ["int-e2e"]),
 t("int-repro", IN, D, "reproduction script", "medium",
   "scripts/reproduce.sh: init db, run the full pytest suite, run demo, print summary; set -e.",
   ["bash scripts/reproduce.sh exits 0 on a clean tree"],
   ["scripts/reproduce.sh"], ["int-e2e"]),
 t("int-readme", IN, D, "README.md (8 proof sections)", "medium",
   "README.md for the proof with all 8 PROOF_SPEC sections: What was built, Why this proof exists, Final architecture, Commands, Reproduce, Artifact index, Behavior notes, Lessons learned.",
   ["README.md contains all 8 required sections",
    "Commands section references run_agents.py and demo/run_demo.py"],
   ["README.md"], ["int-e2e"]),
 t("int-verify-matrix", IN, D, "verification gate matrix", "high",
   "scripts/verify.sh: runs compileall, full pytest, demo script, and the DAG invariants check; prints 'ALL GREEN'.",
   ["bash scripts/verify.sh exits 0 and prints 'ALL GREEN'"],
   ["scripts/verify.sh"], ["int-e2e", "int-readme"]),
]

# --------------------------------------------------------------- assembly
assert len(T) >= 110, f"need >= 110 tasks, have {len(T)}"
ids = [x["id"] for x in T]
assert len(ids) == len(set(ids)), "duplicate task ids"
all_deps = [d for x in T for d in x["deps"]]
assert set(all_deps) <= set(ids), "dependency references unknown task"
assert not any(tid in x["deps"] for x in T for tid in [x["id"]]), "self-dependency"

SUBSYSTEM_LABELS = {
    F: "foundation", CT: "contract", ST: "storage", AU: "auth", GW: "gateway",
    WK: "worker", CL: "cli", OB: "observe", IN: "integration",
}
AGENT_LABELS = {A: "agent-a (foundation+contract+gateway)",
                B: "agent-b (storage+auth)",
                C: "agent-c (worker+cli)",
                D: "agent-d (observe+integration)"}

events = []
for x in sorted(T, key=lambda x: x["id"]):
    events.append({
        "op": "task_created",
        "id": x["id"],
        "title": x["title"],
        "description": x["description"],
        "acceptance": x["acceptance"],
        "files": x["files"],
        "priority": x["priority"],
        "notes": [f"subsystem: {SUBSYSTEM_LABELS[x['subsystem']]}",
                  f"owner: {AGENT_LABELS[x['agent']]}"],
    })
for x in sorted(T, key=lambda x: x["id"]):
    for d in sorted(x["deps"]):
        events.append({"op": "dependency_added", "task": x["id"], "depends_on": d})

proposal = {
    "proposal_id": "prop_swarm_001",
    "reason": ("Proof #5: a 118-task multi-agent stress proof answering C4 "
               "(long projects) and C5 (multi-agent). One shared Forge project "
               "implemented by 4 concurrent agent processes across 9 subsystems "
               "(foundation, contract, storage, auth, gateway, worker, cli, "
               "observe, integration). Public SDK/CLI only; kernel frozen."),
    "confidence": 0.8,
    "events": events,
}

subsystems = {"agents": {}, "subsystems": {}}
for x in T:
    sub, ag = x["subsystem"], x["agent"]
    subsystems["agents"].setdefault(ag, {"label": AGENT_LABELS[ag], "tasks": []})
    subsystems["agents"][ag]["tasks"].append(x["id"])
    subsystems["subsystems"].setdefault(sub, {"label": SUBSYSTEM_LABELS[sub],
                                              "agent": ag, "tasks": []})
    subsystems["subsystems"][sub]["tasks"].append(x["id"])

with open(os.path.join(OUT_DIR, "proposal.json"), "w", encoding="utf-8") as f:
    json.dump(proposal, f, indent=2, ensure_ascii=False)
    f.write("\n")
with open(os.path.join(OUT_DIR, "subsystems.json"), "w", encoding="utf-8") as f:
    json.dump(subsystems, f, indent=2, ensure_ascii=False)
    f.write("\n")

n_agents = len(subsystems["agents"])
print(f"wrote proposal.json: {len(T)} tasks, {len(events)} events "
      f"({len(T)} created + {len(events) - len(T)} deps), {len(SUBSYSTEM_LABELS)} "
      f"subsystems, {n_agents} agents")
for ag, info in subsystems["agents"].items():
    print(f"  {ag}: {len(info['tasks'])} tasks")