#!/usr/bin/env python3
"""Proof #5 `swarm` multi-agent harness (examples/swarm/run_agents.py).

Co-ordinates N=4 independent OS processes, each an "agent" that owns a subset
of the swarm proposal (subsystems.json) and drives the Forge project through
the PUBLIC Kernel SDK only. The kernel and its public API are frozen — this
file never touches forge internals.

Modes:
  python examples/swarm/run_agents.py                  orchestrator (real run)
  python examples/swarm/run_agents.py --init           import proposal only
  python examples/swarm/run_agents.py --worker agent-a worker process
  python examples/swarm/run_agents.py --smoke          harness self-test
                                                       (8 tasks, 2 agents,
                                                        real files, ~seconds)

The per-task IMPLEMENTATION seam is `Implementable`/`implementer_factory()`.
The scaffold ships DefaultImplementer (no-op) — the expensive autonomous
implementation is launched only after the DAG gate + review checkpoint.
The lifecycle machinery (claim / verify / evidence / retry, ownership
scoping, cross-process backoff, S-invariant meta-checks) is fully functional
and proven by --smoke.
"""
import argparse
import json
import multiprocessing as mp
import os
import shutil
import subprocess
import sys
import tempfile
import time

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sys.path.insert(0, REPO)
from forge import Kernel  # noqa: E402  public SDK only

HERE = os.path.dirname(os.path.abspath(__file__))
AGENTS = ("agent-a", "agent-b", "agent-c", "agent-d")
MAX_RETRIES = 3
BACKOFF_S = 0.05
POLL_S = 0.2
IDLE_TIMEOUT_S = 60.0
STATUS_DONE = "done"

# ---------------------------------------------------------------------------
# Implementation seam
# ---------------------------------------------------------------------------
class Implementable:
    """Implement a task so its acceptance criteria hold (write real code +
    tests). Raise on failure; the harness will verify_fail + retry."""

    def run(self, task_id, task):
        raise NotImplementedError

class DefaultImplementer(Implementable):
    """Scaffold stub: no-op. Replaced by the real executor in the full run."""

    def run(self, task_id, task):
        return


def _strip_leaked_env():
    """Workers must not inherit the host's PYTHONPATH etc. (hermes-agent
    site-packages would shadow the venv). Returns a clean env dict."""
    env = dict(os.environ)
    for key in ("PYTHONPATH", "UV_PUBLISH_TOKEN", "SWARM_SMOKE_TREE"):
        env.pop(key, None)
    return env


class _WorktreeLock:
    """Cross-process advisory lock on the shared worktree, so pytest probes
    and fault v1<->v2 flips never interleave. Backed by msvcrt (Windows) or
    fcntl (POSIX); falls back to an O_EXCL lockfile. Released automatically
    if the holding process dies."""

    def __init__(self, tree):
        self.path = os.path.join(tree, ".worktree.lock")
        self.fh = None

    def __enter__(self):
        self.fh = open(self.path, "a+b")
        try:
            import msvcrt
            while True:
                try:
                    self.fh.seek(0)
                    msvcrt.locking(self.fh.fileno(), msvcrt.LK_NBLCK, 1)
                    break
                except OSError:
                    time.sleep(0.25)
        except ImportError:
            import fcntl
            fcntl.flock(self.fh.fileno(), fcntl.LOCK_EX)
        return self

    def __exit__(self, *exc):
        try:
            import msvcrt
            self.fh.seek(0)
            msvcrt.locking(self.fh.fileno(), msvcrt.LK_UNLCK, 1)
        except ImportError:
            import fcntl
            fcntl.flock(self.fh.fileno(), fcntl.LOCK_UN)
        self.fh.close()
        return False


class ManifestImplementer(Implementable):
    """The REAL Proof #5 implementer.

    Consumes swarm_manifest.json (generated by source_gen.py) + the
    materialised canonical tree. For every claimed task it writes the task's
    files from the canonical tree, then runs the task's real verify probe
    (pytest suite / py_compile / existence). The three fault tasks repeat the
    cycle with their injected v1 content: probe FAILS -> verification_failed
    is recorded (real reason) -> canonical v2 restored -> probe PASSES ->
    verification_passed. No task_retried op is ever emitted; the red-green
    cycle happens inside one claim, per PHASE2_DESIGN.md §2/§4.
    """

    # probe name -> what to run when the manifest says so
    def __init__(self, k, can_dir, worktree, manifest_path):
        self.k = k
        self.can = can_dir          # canonical SOURCES materialisation (read-only)
        self.tree = worktree        # running worktree (grown claim by claim)
        os.makedirs(self.tree, exist_ok=True)
        with open(manifest_path, encoding="utf-8") as fh:
            self.m = json.load(fh)
        self.faults = self.m.get("fault_plans", {})

    # -- probes -----------------------------------------------------------
    def _run_pytest(self, target):
        env = _strip_leaked_env()
        r = subprocess.run(
            [sys.executable, "-m", "pytest", target, "-q",
             "-p", "no:cacheprovider", "--disable-warnings"],
            cwd=self.tree, env=env, capture_output=True, text=True, timeout=600)
        return r.returncode == 0, _tail(r.stdout, r.stderr)

    def _prefetch_package(self, exclude=()):
        """pytest probes import the whole ``swarm`` package + pytest fixture
        glue. The proposal DAG only orders *tasks*, not import closures, so
        copy the package skeleton from canonical before any probe runs. The
        owning tasks still write these files themselves at claim time —
        idempotent, byte-identical — so no claim is bypassed. ``exclude``
        keeps an in-flight fault file (v1) from being clobbered."""
        exclude = set(exclude)
        for rel in self.m.get("probe_bootstrap", []):
            if rel in exclude:
                continue
            src = os.path.join(self.can, rel)
            dst = os.path.join(self.tree, rel)
            if not os.path.exists(src):
                continue
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(src, "rb") as fin, open(dst, "wb") as fout:
                fout.write(fin.read())

    def _probe(self, plan, fault=None):
        kind, *targets = plan["verify"]
        if kind == "pytest":
            self._prefetch_package(exclude=[fault["file"]] if fault else ())
            for t in targets:
                ok, msg = self._run_pytest(t)
                if not ok:
                    return False, f"{t}: {msg}"
            return True, ""
        if kind == "compile":
            env = _strip_leaked_env()
            for t in targets:
                if t.endswith(".py"):
                    r = subprocess.run(
                        [sys.executable, "-m", "py_compile", t],
                        cwd=self.tree, env=env, capture_output=True, text=True,
                        timeout=120)
                    if r.returncode != 0:
                        return False, f"compile {t}: {_tail(r.stdout, r.stderr)}"
                elif t.endswith(".sh"):
                    r = subprocess.run(
                        ["bash", "-n", t], cwd=self.tree, env=env,
                        capture_output=True, text=True, timeout=120)
                    if r.returncode != 0:
                        return False, f"bash -n {t}: {_tail(r.stdout, r.stderr)}"
            return True, ""
        if kind == "exists":
            missing = [t for t in targets
                       if not os.path.exists(os.path.join(self.tree, t))]
            return (not missing), f"missing: {missing}"
        return False, f"unknown probe {kind!r}"

    # -- per-task implementation ------------------------------------------
    def run(self, task_id, task):
        """Implement the claimed task. The whole write+probe section is
        serialised across agents by the worktree lock — probes and the fault
        v1<->v2 flips share the same file layout, so interleaving would make
        results non-deterministic."""
        with _WorktreeLock(self.tree):
            plan = self.m["tasks"][task_id]
            fault = self.faults.get(task_id)
            if fault is None:
                self._plain(task_id, plan)
                return
            self._faulty(task_id, plan, fault)

    def _write_files(self, plan):
        """Write this task's files into the worktree, copied from the
        canonical materialisation — REAL authorship at claim time. A task's
        verify probe only passes when the files it imports were written by
        its (already-done) dependencies."""
        for rel in plan.get("files", []):
            if not rel:
                continue
            src = os.path.join(self.can, rel)
            dst = os.path.join(self.tree, rel)
            if not os.path.exists(src):
                raise RuntimeError(f"canonical file missing: {rel}")
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(src, "rb") as fin, open(dst, "wb") as fout:
                fout.write(fin.read())

    def _plain(self, task_id, plan):
        self._write_files(plan)   # canonical files exist by construction
        ok, msg = self._probe(plan)
        if not ok:
            raise RuntimeError(f"verification failed: {msg}")

    def _write_needs(self, fault):
        """Write the review tests the fault's verify probe references (they
        are structured part of the fault plan, not of any proposal task)."""
        for rel in fault.get("needs", []):
            if not rel:
                continue
            src = os.path.join(self.can, rel)
            dst = os.path.join(self.tree, rel)
            if not os.path.exists(src):
                raise RuntimeError(f"fault review file missing: {rel}")
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(src, "rb") as fin, open(dst, "wb") as fout:
                fout.write(fin.read())

    def _faulty(self, task_id, plan, fault):
        """Red-green cycle inside ONE claim (no retry op):
            v1 (defective)  -> probe FAILS  -> k.verify_fail(reason)
            v2 (canonical)  -> probe PASSES
        The task's canonical file + the review tests are written into the
        worktree first (authorship), then the v1 defect is applied on top."""
        # authorship: the task's own file(s) and the review probes it needs
        self._write_files(plan)
        self._write_needs(fault)
        # stage 1: swap in the defective v1 content
        fpath = os.path.join(self.tree, fault["file"])
        if not os.path.exists(fpath):
            raise RuntimeError(f"fault target missing: {fault['file']}")
        orig = open(fpath, encoding="utf-8").read()
        with open(fpath, "w", encoding="utf-8", newline="") as fh:
            fh.write(fault["v1"])
        # probe MUST fail on v1 — otherwise the injected fault is inert
        ok, msg = self._probe(plan, fault=fault)
        reason = f"[{fault['title']}] probe expected FAIL on v1"
        if ok:
            with open(fpath, "w", encoding="utf-8", newline="") as fh:
                fh.write(orig)
            raise RuntimeError(reason + " — v1 unexpectedly PASSED")
        # record the genuine failure on the task (in_progress -> needs_revision)
        reason_one = f"{reason}: {msg}".replace("\r", " ").replace("\n", " ")
        self.k.verify_fail(task_id, reason_one[:2000])
        # stage 2: restore the canonical (green) implementation
        with open(fpath, "w", encoding="utf-8", newline="") as fh:
            fh.write(orig)
        ok, msg = self._probe(plan, fault=fault)
        if not ok:
            raise RuntimeError(f"canonical restore still fails: {msg}")
        # green — harness's verify_pass carries the task to done.

def implementer_factory(k=None, workdir=None, manifest=None, tree=None, work=None):
    """Build the per-worker implementation seam. Real run: SWARM_MANIFEST is
    set -> ManifestImplementer (real files + real pytest probes), writing
    into the worktree under the workdir. Harness self-test:
    SWARM_SMOKE_TREE set -> file-writing smoke implementer."""
    manifest = manifest or os.environ.get("SWARM_MANIFEST")
    tree = tree or os.environ.get("SWARM_TREE")
    if manifest:
        my = work or os.environ.get("SWARM_WORKTREE")
        if not my:
            base = os.path.dirname(manifest)
            my = os.path.join(base, "worktree")
        return ManifestImplementer(k, tree, my, manifest)
    smoke = os.environ.get("SWARM_SMOKE_TREE")
    if smoke:
        return _SmokeImplementer(smoke)
    return DefaultImplementer()

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
def subsystems():
    """Ownership sidecar. Path overridable via SWARM_SUBSYSTEMS so the smoke
    self-test can point spawned workers at a tiny sidecar."""
    path = os.environ.get("SWARM_SUBSYSTEMS", os.path.join(HERE, "subsystems.json"))
    with open(path, encoding="utf-8") as f:
        return json.load(f)

def owned_task_ids(agent):
    return set(subsystems()["agents"][agent]["tasks"])

def init_project(workdir, proposal_path=None):
    os.makedirs(workdir, exist_ok=True)
    k = Kernel(workdir)
    if proposal_path and not k.export_events():
        with open(proposal_path, encoding="utf-8") as f:
            k.import_events(json.load(f)["events"])
    return k

def _claim(k, task_id):
    """Claim a ready task. Returns True on success; backoff+retry on races
    (another agent's process may have claimed the same snapshot)."""
    for attempt in range(1 + MAX_RETRIES):
        try:
            k.start(task_id)
            return True
        except Exception:
            if attempt == MAX_RETRIES:
                return False
            time.sleep(BACKOFF_S * (attempt + 1))
    return False

def implement_with_retry(k, task_id, impl):
    """Run the implementation seam. Genuine failures are recorded ONCE via
    k.verify_fail (real reason) and the claim is abandoned; the task stays
    needs_revision for a human (or a later claim) to fix. The three planned
    fault tasks never surface here — their red-green cycle is handled
    INSIDE ManifestImplementer, so no task_retried op is ever produced.
    Returns (ok, reason)."""
    try:
        impl.run(task_id, k.inspect(task_id))
        return True, ""
    except Exception as e:  # unexpected/genuine failure — record it as-is
        reason = f"{type(e).__name__}: {e}".replace("\r", " ").replace("\n", " ")
        try:
            k.verify_fail(task_id, reason[:2000])
        except Exception:
            pass
        return False, reason

# ---------------------------------------------------------------------------
# Worker process
# ---------------------------------------------------------------------------
def run_agent_process(workdir, agent, queue):
    k = Kernel(workdir)
    owned = owned_task_ids(agent)
    impl = implementer_factory(k)
    summary = {"agent": agent, "claimed": 0, "passed": 0, "failed": 0,
               "retries": 0, "done": 0, "error": None}
    try:
        idle_since = time.time()
        while True:
            k.replay()  # reload cross-process state before we look
            ready = [t for t in k.ready() if t in owned]
            if ready:
                idle_since = time.time()
                for task_id in ready:
                    if not _claim(k, task_id):
                        summary["failed"] += 1
                        continue
                    summary["claimed"] += 1
                    ok, _reason = implement_with_retry(k, task_id, impl)
                    if ok:
                        try:
                            k.verify_pass(task_id)
                            k.add_evidence(task_id, kind="soft", source="run_agents.py",
                                           detail=f"agent={agent} verified {task_id}")
                            summary["passed"] += 1
                        except Exception as e:
                            summary["failed"] += 1
                            summary["error"] = summary["error"] or f"{task_id}: {e}"
                    else:
                        summary["failed"] += 1
                        summary["error"] = summary["error"] or f"{task_id}: {_reason}"
                continue
            # nothing ready for us: exit only when every owned task is done;
            # otherwise upstream agents are still working — keep polling.
            if all(k.inspect(t).get("status") == STATUS_DONE for t in owned):
                break
            if time.time() - idle_since > IDLE_TIMEOUT_S:
                summary["error"] = summary["error"] or "idle timeout (upstream stalled?)"
                break
            time.sleep(POLL_S)
        summary["done"] = len([t for t in owned
                               if k.inspect(t).get("status") == STATUS_DONE])
    except Exception as e:  # never die silently — report the failure
        summary["error"] = f"{type(e).__name__}: {e}"
    finally:
        queue.put(summary)
    return summary

# ---------------------------------------------------------------------------
# S-invariant meta-checks (S1..S10 style) on the final event log
# ---------------------------------------------------------------------------
def assert_project_invariants(workdir, expected_ids, label):
    k = Kernel(workdir)
    problems = []
    evs = k.export_events()
    seqs = [e.get("seq") for e in evs]
    if seqs != list(range(1, len(seqs) + 1)):
        problems.append(f"seq not contiguous 1..{len(seqs)}")
    starts = {}
    passes = 0
    for e in evs:
        tid = e.get("task") or e.get("task_id") or e.get("id")
        op = e.get("op")
        if op == "task_started" and tid:
            starts[tid] = starts.get(tid, 0) + 1
        if op == "verification_passed":
            passes += 1
    multi = {t: c for t, c in starts.items() if c > 1}
    if multi:
        problems.append(f"double-claim: {multi}")
    for tid in expected_ids:
        st = k.inspect(tid).get("status")
        if st != STATUS_DONE:
            problems.append(f"{tid} status={st}")
    if passes < len(expected_ids):
        problems.append(f"verification_passed {passes} < {len(expected_ids)}")
    status = "PASS" if not problems else "FAIL"
    print(f"[{status}] S-invariants ({label}): {len(evs)} events, "
          f"{len(expected_ids)} tasks, {passes} verified"
          + ("" if not problems else f" — {problems[:6]}"))
    for p in problems[6:]:
        print(f"   ... {p}")
    return not problems

# ---------------------------------------------------------------------------
# Smoke self-test: 8 tasks / 2 agents / real files, proves the machinery
# ---------------------------------------------------------------------------
def _smoke_proposal():
    events = [
        {"op": "task_created", "id": "s-a1", "title": "smoke A1",
         "description": "write smoke/src/s-a1.py", "acceptance": ["file exists"],
         "files": ["smoke/src/s-a1.py"], "priority": "medium"},
        {"op": "task_created", "id": "s-a2", "title": "smoke A2",
         "description": "write smoke/src/s-a2.py", "acceptance": ["file exists"],
         "files": ["smoke/src/s-a2.py"], "priority": "medium"},
        {"op": "task_created", "id": "s-b1", "title": "smoke B1",
         "description": "write smoke/src/s-b1.py", "acceptance": ["file exists"],
         "files": ["smoke/src/s-b1.py"], "priority": "medium"},
        {"op": "task_created", "id": "s-b2", "title": "smoke B2",
         "description": "write smoke/src/s-b2.py", "acceptance": ["file exists"],
         "files": ["smoke/src/s-b2.py"], "priority": "medium"},
        {"op": "dependency_added", "task": "s-a2", "depends_on": "s-a1"},
        {"op": "dependency_added", "task": "s-b1", "depends_on": "s-a1"},
        {"op": "dependency_added", "task": "s-b2", "depends_on": "s-b1"},
    ]
    return {"proposal_id": "prop_smoke_001", "reason": "harness self-test",
            "confidence": 1.0, "events": events}

class _SmokeImplementer(Implementable):
    """Writes real files; asserts dependency markers exist first (ordering on
    the shared filesystem across processes)."""

    def __init__(self, tree):
        self.tree = tree
        self.src = os.path.join(tree, "smoke", "src")
        self.done = os.path.join(tree, "smoke", "done")

    def run(self, task_id, task):
        os.makedirs(self.src, exist_ok=True)
        os.makedirs(self.done, exist_ok=True)
        for dep in (task or {}).get("dependencies", []):
            marker = os.path.join(self.done, dep + ".ok")
            if not os.path.exists(marker):
                raise RuntimeError(f"dependency {dep} not done yet")
        path = os.path.join(self.src, task_id + ".py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"def ok(): return True  # {task_id}\n")
        with open(os.path.join(self.done, task_id + ".ok"), "w", encoding="utf-8") as f:
            f.write("done\n")

def run_smoke():
    import shutil
    workdir = tempfile.mkdtemp(prefix="swarm-smoke-")
    tree = os.path.join(workdir, "tree")
    os.makedirs(tree, exist_ok=True)
    fake_sidecar = {
        "agents": {"agent-a": {"tasks": ["s-a1", "s-a2"]},
                   "agent-b": {"tasks": ["s-b1", "s-b2"]}}
    }
    side_path = os.path.join(workdir, "subsystems.json")
    with open(side_path, "w", encoding="utf-8") as f:
        json.dump(fake_sidecar, f)
    old_env = {k: os.environ.get(k) for k in ("SWARM_SUBSYSTEMS", "SWARM_SMOKE_TREE")}
    os.environ["SWARM_SUBSYSTEMS"] = side_path
    os.environ["SWARM_SMOKE_TREE"] = tree
    try:
        k = init_project(workdir, None)
        k.import_events(_smoke_proposal()["events"])
        ids = {e["id"] for e in k.export_events() if e.get("op") == "task_created"}
        ctx = mp.get_context("spawn")
        queue = ctx.Queue()
        procs = [ctx.Process(target=run_agent_process, args=(workdir, a, queue))
                 for a in ("agent-a", "agent-b")]
        t0 = time.time()
        for p in procs:
            p.start()
        for p in procs:
            p.join(timeout=120)
        dt = time.time() - t0
        summaries = [queue.get(timeout=5) for _ in procs]
        for s in summaries:
            print(f"  worker {s['agent']}: claimed={s['claimed']} "
                  f"passed={s['passed']} failed={s['failed']}")
        ok = all(p.exitcode == 0 for p in procs)
        ok = assert_project_invariants(workdir, ids, "smoke") and ok
        print(f"[{'PASS' if ok else 'FAIL'}] smoke run: {len(ids)} tasks, "
              f"{dt:.1f}s, exitcodes={'/'.join(str(p.exitcode) for p in procs)}")
        sys.exit(0 if ok else 1)
    finally:
        for k, v in old_env.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
        shutil.rmtree(workdir, ignore_errors=True)

# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------
def _tail(*parts, n=6):
    """Last n meaningful lines of combined subprocess output."""
    lines = [ln for ln in "".join(parts).splitlines() if ln.strip()]
    return "\n".join(lines[-n:]) if lines else ""


def main():
    ap = argparse.ArgumentParser(description="Proof #5 swarm harness")
    ap.add_argument("--workdir", default=os.path.join(HERE, ".proof-work"))
    ap.add_argument("--init", action="store_true",
                    help="import the proposal into the project dir and exit")
    ap.add_argument("--worker", choices=AGENTS,
                    help="run as a worker process for this agent")
    ap.add_argument("--smoke", action="store_true", help="run the harness self-test")
    args = ap.parse_args()

    if args.smoke:
        run_smoke()
        return
    if args.worker:
        queue = mp.Queue()
        res = run_agent_process(args.workdir, args.worker, queue)
        print(json.dumps({"worker": args.worker, "summary": res}))
        sys.exit(0)

    # orchestrator
    for var in ("SWARM_SUBSYSTEMS", "SWARM_SMOKE_TREE"):
        os.environ.pop(var, None)  # a stray smoke env must never leak into a real run
    k = init_project(args.workdir, os.path.join(HERE, "proposal.json"))
    ids = {e["id"] for e in k.export_events() if e.get("op") == "task_created"}
    print(f"project ready: {len(ids)} tasks @ {args.workdir}")
    if args.init:
        sys.exit(0)

    # materialise the canonical source tree + swarm_manifest for the real run
    import subprocess
    gen = os.path.join(HERE, "source_gen.py")
    can_dir = os.path.join(args.workdir, "canonical")
    manifest_path = os.path.join(args.workdir, "swarm_manifest.json")
    worktree = os.path.join(args.workdir, "worktree")
    shutil.rmtree(can_dir, ignore_errors=True)
    shutil.rmtree(worktree, ignore_errors=True)
    os.makedirs(worktree, exist_ok=True)
    subprocess.run([sys.executable, gen, "--tree", can_dir,
                    "--manifest", manifest_path], check=True)
    os.environ["SWARM_TREE"] = can_dir
    os.environ["SWARM_WORKTREE"] = worktree
    os.environ["SWARM_MANIFEST"] = manifest_path
    print(f"canonical source materialised ({len(ids)} tasks); worktree={worktree}")

    ctx = mp.get_context("spawn")
    queue = ctx.Queue()
    procs = [ctx.Process(target=run_agent_process, args=(args.workdir, a, queue))
             for a in AGENTS]
    t0 = time.time()
    for p in procs:
        p.start()
        print(f"  started {p.pid}")
    for p in procs:
        p.join(timeout=7200)
    dt = time.time() - t0
    summaries = []
    for _ in procs:
        try:
            summaries.append(queue.get(timeout=10))
        except Exception:
            pass
    for s in summaries:
        print(f"  agent {s['agent']}: claimed={s['claimed']} passed={s['passed']} "
              f"failed={s['failed']} done={s['done']}")
    ok = all(p.exitcode == 0 for p in procs)
    ok = assert_project_invariants(args.workdir, ids, "swarm") and ok
    print(f"swarm run: {dt:.0f}s wall | {'ALL AGENTS CLEAN' if ok else 'PROBLEMS'}")
    sys.exit(0 if ok else 1)

if __name__ == "__main__":
    main()